#################################################################################
# Based off : https://github.com/Azure/bicep/blob/main/.pipelines/OneBranch.Official.yml
#################################################################################

# https://aka.ms/obpipelines/triggers
trigger:
  batch: true
  branches:
    include:
      - main

parameters: # parameters are shown up in ADO UI in a build queue time
  - name: "debug"
    displayName: "Enable debug output"
    type: boolean
    default: false

variables:
  system.debug: ${{ parameters.debug }}

  BuildSolution: $(Build.SourcesDirectory)/Alwin.sln
  BuildConfiguration: Release
  TargetFramework: net5.0

stages:
  - template: Common.yml
